# .github/workflows/update_presets_and_deploy.yml
name: Update Presets JSON and Deploy

on:
  push:
    branches:
      - master  # Trigger on pushes to main

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate presets.json in the repo root
      - name: Generate presets.json
        run: |
          files=()
          while IFS= read -r -d $'\0' file; do
            files+=("$file")
          done < <(find presets/ -maxdepth 1 -type f -print0)

          python3 - <<EOF
import json
import os

files = [f.replace("\\\\","/") for f in ${files[@]}]
json_list = json.dumps([f for f in files], indent=2)
with open("presets.json", "w") as f:
    f.write(json_list)
EOF

          echo "Generated presets.json:"
          cat presets.json

      # 3. Commit and push the generated JSON if it changed
      - name: Commit updated presets.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add presets.json
          git diff --quiet || git commit -m "Update presets.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
